networks:
  hadoop:
    driver: bridge
# docker restart container hadoop-master
services:
  hadoop-master:
    image: uracilo/hadoop
    container_name: hadoop-master
    hostname: hadoop-master
    networks:
      - hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
    tty: true

  hadoop-slave1:
    image: uracilo/hadoop
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    networks:
      - hadoop
    tty: true

  hadoop-slave2:
    image: uracilo/hadoop
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    networks:
      - hadoop
    tty: true

  hadoop-slave3:
    image: uracilo/hadoop
    container_name: hadoop-slave3
    hostname: hadoop-slave3
    networks:
      - hadoop
    tty: true

  hadoop-slave4:
    image: uracilo/hadoop
    container_name: hadoop-slave4
    hostname: hadoop-slave4
    networks:
      - hadoop
    tty: true
